#The indicator color for normal hits
HitColor: "7"

#The indicator color for critical hits
CriticalHitColor: "4"

#Should the indicator be shown to everyone(true) or just the damager(false)
#! DON"T RELOAD THE SERVER AFTER CHANGING THIS VALUE INSTEAD RESTART
ShowToDamagerOnly: true

#The format for showing the damage (example: "0.0#❤")
#https://docs.oracle.com/javase/7/docs/api/java/text/DecimalFormat.html
IndicatorFormat: "0.#"
